### ISSUE TITLE
[BE] Config lại base code cho hệ thống

### ISSUE THREAD

**Issue by vietcoder1998** [vietcoder1998/x-ray-diagnostic-service#1]
## MÔ TẢ
- Thay đổi lại service nghiệp vụ hệ thống như sau:
1. User sẽ quản lý theo branchId của họ
2. Authenticate sẽ thay đổi như sau:
- Một user sẽ có 1 role
- 1 role sẽ có 1 hoặc nhiều permission
- Một permission sẽ có 1 hoặc nhiều module
- User sẽ có thể access dựa vào Role của họ
- Người dùng khi đăng ký hệ thống sẽ có Role cơ bản là Public user
- Admin User chỉ được khởi tạo từ DB
3. Thay đổi luồng Authenticate:
- Người dùng khi Authenticate -> lấy token rồi dựa vào token, lấy role, check role, check permission
5. Thay đổi DB của user:
- Bổ sung thêm BranchID
- Bổ sung mặc định cơ bản role là role public_user
- Thay đổi quan hệ giữa role, module -> role, permission, module

## TODO

- [ ] - Thay đổi lại kiến trúc của User - 2h
- [ ] - Bổ sung thêm Permission - 1h
- [ ] - Bổ sung thêm Quan hệ giữa Permission Entity và Module Entity 1h
- [ ] - Thay đổi lại luồng Authenticate và Cấu trúc lại Token  1h
- [ ] - Bổ sung thêm vào API Doc - 0.5h
- [ ] - Test lại luồng Authenticate mới - 0.5h
